# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Webjeda cards
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Webjeda Cards is a Bootstrap based jekyll theme for portfolio, photography or any kind of blog.
  
  
  
baseurl: "/cards" # the subpath of your site, e.g. /blog
url: "http://webjeda.com" # the base hostname & protocol for your site

#footer
built-by: webjeda

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 9
paginate_path: /page:num/


#social
facebook: http://facebook.com/webjeda
quora: http://quora.com/sharathdt
twitter: http://twitter.com/@webjeda
github: http://github.com/webjeda

#facebook like box
fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/webjeda/
fb-page-title: webjeda

sass:
  style: compressed

gems: [jekyll-paginate]