# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: El Mundo Es Imperfecto
email: web@elmundoesimperfecto.com
description: > # this means to ignore newlines until "baseurl:"
  My personal aggregator. Based on Webjeda Cards is a Bootstrap based jekyll theme for portfolio, photography or any kind of blog.
  
#baseurl: "/cards" # the subpath of your site, e.g. /blog
url: "https://elmundoesimperfecto.com" # the base hostname & protocol for your site
baseurl: "/" # the subpath of your site, e.g. /blog
  # =======
  # title: Personal Aggregator
  # email: your-email@domain.com
  # description: > # this means to ignore newlines until "baseurl:"
  #   A theme based on Webjeda.
  # 
  # 
  # #baseurl: "/cards" # the subpath of your site, e.g. /blog
  # #url: "https://elmundoesimperfecto.com" # the base hostname & protocol for your site
  # url: "" # the base hostname & protocol for your site
  # >>>>>>> e7648390bc741ad5b63096fff6cdb5db0c0f97ce

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: fernand0 based on webjeda's work

  # copyright:
  # <<<<<<< HEAD
   name: Fernando Tricas GarcÃ­a & webjeda (for the original template)
   link: 'http://elmundoesimperfecto.com'
     # =======
     #    name: fernand0 / webjeda
     #    link: 'https://elmundoesimperfecto.com/'
     # >>>>>>> e7648390bc741ad5b63096fff6cdb5db0c0f97ce

# Build settings
permalink: /:title/
paginate: 100
paginate_path: /page:num/

# Tracker
# analytics: UA-83979019-1

# Comments
# disqus: yes
# disqus-shortname: webjeda-demo
# disqus-shortname: some-user

#social
facebook: http://facebook.com/fernando.tricas
twitter: http://twitter.com/fernand0
github: http://github.com/fernand0
email: fernand0+web@elmundoesimperfecto.com

# #facebook like box
# fb-like-box: yes
# fb-app-id: 123456789012345
# fb-page-url: https://www.facebook.com/somePage/
# fb-page-title: someTitle

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins:
  - jekyll-seo-tag
  #  - jekyll-paginate
