---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: JTemporal
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
- type: heading
  label: Tema
- type: directory
  path: _scss
  label: StyleSheets
  create: all
  match: "**/*"
  new_doc_ext: ".scss"
- type: directory
  path: _layouts
  label: Layouts
  create: documents
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: _includes
  label: Includes
  create: documents
  match: "**/*"
  new_doc_ext: html
upload_dir: images
public_path: images
front_matter_path: "/images"
use_front_matter_path: true
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --config _dev_config.yml --drafts
    --unpublished --future --port 8080 --host 0.0.0.0 -d _site
  publish_command: bundle exec jekyll build -d _site
  publish_env:
  - JEKYLL_ENV=production
  output_directory: _site
  preview_command: 'bundle exec jekyll build --config _dev_config.yml --drafts --unpublished
    --future -d _site '
